# Generated by Django 4.2.8 on 2024-11-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='qqq', max_length=10000),
        ),
    ]
