version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    networks:
      - my_network

  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    external: true
